### ISSUE TITLE
creepy function

### ISSUE THREAD

**Issue by paulin-mipt** [Ekateriner/Text-generator#4]
https://github.com/Ekateriner/Text-generator/blob/f0106da76965e2303dd04aaf6cf18099889a77c7/training.py#L9

Это какая-то страшная функция. Серьёзно, даже мне жутковато на неё смотреть. Её смысл непонятен с первого взгляда (второго, третьего...), а ещё она разделена на насколько частей и состоит из очень-очень похожих кусков кода. Такой антипаттерн программирования иногда называют boilerplate, и я уверена, что это можно обобщить и сократить раз эдак в десять. Кстати, обратите внимание на строковые методы isalpha(), isnum() и им подобные

Попробуйте, должно получиться!

**Comment by Ekateriner** [comment]
теперь все исправленно
